/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SideMenus;
import AdminPanels.AttendanceList;
import AdminPanels.DutyRoster;
import AdminPanels.TeamsAndMembers;
import ManagementUi.AdminMain;
import ManagementUi.Login;
import app.mavenproject2.SideTabButton;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;

/**
 *
 * @author HP
 */
public class Adminpanel extends javax.swing.JPanel {
    private AdminMain parent;
   
    private List<JButton> tabButtons;
    private List<String> cardNames;
    private DutyRoster dutyRoster;
    private AttendanceList attendanceList;
    private TeamsAndMembers teamsAndmembers;
    /**
     * Creates new form MenuPanels
     */
    public Adminpanel(AdminMain parent, DutyRoster dutyRoster, AttendanceList attendanceList, TeamsAndMembers teamsAndmembers) {
        this.parent = parent;
        this.dutyRoster = dutyRoster;
        this.teamsAndmembers = teamsAndmembers;
        initComponents();

       
        tabButtons = Arrays.asList(AttendanceButton, DutyRosterButton, LeaveAssignmentButton,  PayrollButton,  TeamsAndMembersButton, UserControlButton,DataConfigurationButton,matrixButton, Logout);
        cardNames = Arrays.asList("attendanceList", "dutyRoster", "assign", "pay", "teamsAndmembers", "control", "dataconfig", "matrix","logout");

       
        Consumer<Integer> setActiveTab = idx -> {
            for (int i = 0; i < tabButtons.size(); i++) {
                if (i == idx) {
                    tabButtons.get(i).setBackground(new Color(51, 51, 51));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(true);
                    tabButtons.get(i).setContentAreaFilled(true);
                } else {
                    tabButtons.get(i).setBackground(new Color(0, 0, 0, 0));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(false);
                    tabButtons.get(i).setContentAreaFilled(false);
                }
                tabButtons.get(i).setBorderPainted(false);
            }
            parent.setActiveTab(idx, cardNames); // Call AdminMain to switch form
        };

        // Add listeners to each button
        for (int i = 0; i < tabButtons.size(); i++) {
            final int idx = i;
            tabButtons.get(i).addActionListener(e -> setActiveTab.accept(idx));
        }

        // Set the first tab as active by default
        setActiveTab.accept(0);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        AttendanceButton = new SideTabButton("HR1");
        DutyRosterButton = new SideTabButton("HR2");
        LeaveAssignmentButton = new SideTabButton("HR7");
        PayrollButton = new SideTabButton("HR5");
        Logout = new SideTabButton("HR6");
        TeamsAndMembersButton = new SideTabButton("HR5");
        matrixButton = new SideTabButton("HR5");
        jLabel1 = new javax.swing.JLabel();
        UserControlButton = new SideTabButton("HR5");
        DataConfigurationButton = new SideTabButton("HR5");

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(81, 81, 81));
        setPreferredSize(new java.awt.Dimension(180, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        AttendanceButton.setText("Attendance");
        AttendanceButton.setPreferredSize(new java.awt.Dimension(95, 40));
        add(AttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 40));

        DutyRosterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DutyRosterButton.setForeground(new java.awt.Color(255, 255, 255));
        DutyRosterButton.setText("Duty Roster");
        DutyRosterButton.setPreferredSize(new java.awt.Dimension(97, 40));
        DutyRosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DutyRosterButtonActionPerformed(evt);
            }
        });
        add(DutyRosterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 40));

        LeaveAssignmentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaveAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        LeaveAssignmentButton.setText("Leave Assignment");
        LeaveAssignmentButton.setPreferredSize(new java.awt.Dimension(131, 40));
        add(LeaveAssignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, -1));

        PayrollButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PayrollButton.setForeground(new java.awt.Color(255, 255, 255));
        PayrollButton.setText("Payroll");
        PayrollButton.setPreferredSize(new java.awt.Dimension(72, 40));
        add(PayrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, -1));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, -1));

        TeamsAndMembersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TeamsAndMembersButton.setForeground(new java.awt.Color(255, 255, 255));
        TeamsAndMembersButton.setText("Teams & Members");
        TeamsAndMembersButton.setPreferredSize(new java.awt.Dimension(135, 40));
        TeamsAndMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamsAndMembersButtonActionPerformed(evt);
            }
        });
        add(TeamsAndMembersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, -1));

        matrixButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        matrixButton.setForeground(new java.awt.Color(255, 255, 255));
        matrixButton.setText("Access Matrix");
        matrixButton.setPreferredSize(new java.awt.Dimension(100, 40));
        matrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixButtonActionPerformed(evt);
            }
        });
        add(matrixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administration");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, -1));

        UserControlButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserControlButton.setForeground(new java.awt.Color(255, 255, 255));
        UserControlButton.setText("User Control");
        UserControlButton.setPreferredSize(new java.awt.Dimension(100, 40));
        UserControlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserControlButtonActionPerformed(evt);
            }
        });
        add(UserControlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, -1));

        DataConfigurationButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DataConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        DataConfigurationButton.setText("Data Configuration");
        DataConfigurationButton.setPreferredSize(new java.awt.Dimension(100, 40));
        DataConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataConfigurationButtonActionPerformed(evt);
            }
        });
        add(DataConfigurationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DutyRosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DutyRosterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DutyRosterButtonActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        parent.dispose();
        new Login().setVisible(true);
        
                
    }//GEN-LAST:event_LogoutActionPerformed

    private void matrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrixButtonActionPerformed

    private void TeamsAndMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamsAndMembersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamsAndMembersButtonActionPerformed

    private void UserControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserControlButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserControlButtonActionPerformed

    private void DataConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataConfigurationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataConfigurationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttendanceButton;
    private javax.swing.JButton DataConfigurationButton;
    private javax.swing.JButton DutyRosterButton;
    private javax.swing.JButton LeaveAssignmentButton;
    private javax.swing.JButton Logout;
    private javax.swing.JButton PayrollButton;
    private javax.swing.JButton TeamsAndMembersButton;
    private javax.swing.JButton UserControlButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton matrixButton;
    // End of variables declaration//GEN-END:variables
}
