/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SideMenus;
import AdminPanels.AttendanceList;
import AdminPanels.DutyRoster;
import AdminPanels.TeamsAndMembers;
import app.mavenproject2.SideTabButton;
import ManagementUi.AdminMain;
import ManagementUi.Login;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
/**
 *
 * @author HP
 */
public class HRpanel extends javax.swing.JPanel {
    private AdminMain parent;
    private List<JButton> tabButtons;
    private List<String> cardNames;
    private DutyRoster dutyRoster;
    private AttendanceList attendanceList;
    private TeamsAndMembers teamsAndmembers;
    /**
     * Creates new form MenuPanels
     */
    public HRpanel(AdminMain parent, DutyRoster dutyRoster, AttendanceList attendanceList, TeamsAndMembers teamsAndmemebers) {
        this.parent = parent;
        this.dutyRoster= dutyRoster;
        this.attendanceList = attendanceList;
        this.teamsAndmembers = teamsAndmembers;
        initComponents();
        tabButtons = Arrays.asList(StaffRegistrationButton, LeaveAssignmentButton, RosterAssignmentButton, TeamsAndMembersButton, AttendanceButton, PayrollButton, LogoutButton);
        cardNames = Arrays.asList("registerhr", "assign", "dutyRoster", "teamsAndmembers", "attendanceList", "pay", "logout");

        // Helper to set the active tab and update button styles
        Consumer<Integer> setActiveTab = idx -> {
            for (int i = 0; i < tabButtons.size(); i++) {
                if (i == idx) {
                    tabButtons.get(i).setBackground(new Color(51, 51, 51));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(true);
                    tabButtons.get(i).setContentAreaFilled(true);
                } else {
                    tabButtons.get(i).setBackground(new Color(0, 0, 0, 0));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(false);
                    tabButtons.get(i).setContentAreaFilled(false);
                }
                tabButtons.get(i).setBorderPainted(false);
            }
            parent.setActiveTab(idx, cardNames); // Call AdminMain to switch form
        };

        // Add listeners to each button
        for (int i = 0; i < tabButtons.size(); i++) {
            final int idx = i;
            tabButtons.get(i).addActionListener(e -> setActiveTab.accept(idx));
        }

        // Set the first tab as active by default
        setActiveTab.accept(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        StaffRegistrationButton = new SideTabButton("HR1");
        LeaveAssignmentButton = new SideTabButton("HR2");
        RosterAssignmentButton = new SideTabButton("HR7");
        TeamsAndMembersButton = new SideTabButton("HR3");
        AttendanceButton = new SideTabButton("HR4");
        PayrollButton = new SideTabButton("HR5");
        LogoutButton = new SideTabButton("HR6");
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(81, 81, 81));
        setPreferredSize(new java.awt.Dimension(180, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffRegistrationButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StaffRegistrationButton.setForeground(new java.awt.Color(255, 255, 255));
        StaffRegistrationButton.setText("Staff Registration");
        StaffRegistrationButton.setPreferredSize(new java.awt.Dimension(129, 40));
        StaffRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRegistrationButtonActionPerformed(evt);
            }
        });
        add(StaffRegistrationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, -1));

        LeaveAssignmentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaveAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        LeaveAssignmentButton.setText("Leave Assigment");
        LeaveAssignmentButton.setPreferredSize(new java.awt.Dimension(129, 40));
        add(LeaveAssignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, -1));

        RosterAssignmentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RosterAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        RosterAssignmentButton.setText("Roster Assignment");
        RosterAssignmentButton.setPreferredSize(new java.awt.Dimension(129, 40));
        add(RosterAssignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, -1));

        TeamsAndMembersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TeamsAndMembersButton.setForeground(new java.awt.Color(255, 255, 255));
        TeamsAndMembersButton.setText("Team & Members");
        TeamsAndMembersButton.setPreferredSize(new java.awt.Dimension(129, 40));
        add(TeamsAndMembersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, -1));

        AttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        AttendanceButton.setText("Attendance");
        AttendanceButton.setPreferredSize(new java.awt.Dimension(129, 40));
        add(AttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, -1));

        PayrollButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PayrollButton.setForeground(new java.awt.Color(255, 255, 255));
        PayrollButton.setText("Payroll");
        PayrollButton.setPreferredSize(new java.awt.Dimension(129, 40));
        add(PayrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 180, -1));

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Human Resources");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        parent.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void StaffRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRegistrationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffRegistrationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttendanceButton;
    private javax.swing.JButton LeaveAssignmentButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton PayrollButton;
    private javax.swing.JButton RosterAssignmentButton;
    private javax.swing.JButton StaffRegistrationButton;
    private javax.swing.JButton TeamsAndMembersButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
