/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SideMenus;
import app.mavenproject2.SideTabButton;
import  ManagementUi.AdminMain;
import ManagementUi.Login;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
/**
 *
 * @author HP
 */
public class NormalUserpanel extends javax.swing.JPanel {
    private AdminMain parent;
    private List<JButton> tabButtons;
    private List<String> cardNames;
    /**
     * Creates new form MenuPanels
     */
    public NormalUserpanel(AdminMain parent) {
        this.parent = parent;
        initComponents();
        
        tabButtons = Arrays.asList(LeaveApplicationButton, PaySlipButton, LogoutButton);
        cardNames = Arrays.asList("leave", "paynormal","logout");

        // Helper to set the active tab and update button styles
        Consumer<Integer> setActiveTab = idx -> {
            for (int i = 0; i < tabButtons.size(); i++) {
                if (i == idx) {
                    tabButtons.get(i).setBackground(new Color(51, 51, 51));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(true);
                    tabButtons.get(i).setContentAreaFilled(true);
                } else {
                    tabButtons.get(i).setBackground(new Color(0, 0, 0, 0));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(false);
                    tabButtons.get(i).setContentAreaFilled(false);
                }
                tabButtons.get(i).setBorderPainted(false);
            }
            parent.setActiveTab(idx, cardNames); // Call AdminMain to switch form
        };

        // Add listeners to each button
        for (int i = 0; i < tabButtons.size(); i++) {
            final int idx = i;
            tabButtons.get(i).addActionListener(e -> setActiveTab.accept(idx));
        }

        // Set the first tab as active by default
        setActiveTab.accept(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        LeaveApplicationButton = new SideTabButton("HR1");
        PaySlipButton = new SideTabButton("HR2");
        LogoutButton = new SideTabButton("HR6");
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(81, 81, 81));
        setPreferredSize(new java.awt.Dimension(180, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaveApplicationButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaveApplicationButton.setForeground(new java.awt.Color(255, 255, 255));
        LeaveApplicationButton.setText("Leave Application");
        LeaveApplicationButton.setPreferredSize(new java.awt.Dimension(128, 40));
        add(LeaveApplicationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, -1));

        PaySlipButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PaySlipButton.setForeground(new java.awt.Color(255, 255, 255));
        PaySlipButton.setText("get Payslip");
        PaySlipButton.setPreferredSize(new java.awt.Dimension(128, 40));
        add(PaySlipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, -1));

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
       parent.dispose();
       new Login().setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LeaveApplicationButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton PaySlipButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

       

}
