/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SideMenus;
import AdminPanels.AttendanceList;
import AdminPanels.DutyRoster;
import AdminPanels.TeamsAndMembers;
import app.mavenproject2.SideTabButton;
import java.util.List;
import javax.swing.JButton;
import ManagementUi.AdminMain;
import ManagementUi.Login;
import java.awt.Color;
import java.util.Arrays;
import java.util.function.Consumer;


/**
 *
 * @author HP
 */
public class TEAMLEADERpanel extends javax.swing.JPanel {
    private AdminMain parent;
    private List<JButton> tabButtons;
    private List<String> cardNames;
    private DutyRoster dutyRoster;
    private AttendanceList attendanceList;
    private TeamsAndMembers teamsAndmembers;
    /**
     * Creates new form MenuPanels
     */
    public TEAMLEADERpanel(AdminMain parent, DutyRoster dutyRoster, AttendanceList attendanceList, TeamsAndMembers teamsAndmembers) {
        this.parent = parent;
        this.dutyRoster = dutyRoster;
        this.attendanceList= attendanceList;
        this.teamsAndmembers = teamsAndmembers;
        initComponents();
        tabButtons = Arrays.asList(LeaveManagementButton, RosterAssignmentButton, TeamsAndMembersButton, StaffAttendanceButton, LogoutButton);
        cardNames = Arrays.asList("lm", "dutyRoster", "teamsAndmembers", "attendanceList", "logout");

        // Helper to set the active tab and update button styles
        Consumer<Integer> setActiveTab = idx -> {
            for (int i = 0; i < tabButtons.size(); i++) {
                if (i == idx) {
                    tabButtons.get(i).setBackground(new Color(51, 51, 51));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(true);
                    tabButtons.get(i).setContentAreaFilled(true);
                } else {
                    tabButtons.get(i).setBackground(new Color(0, 0, 0, 0));
                    tabButtons.get(i).setForeground(Color.WHITE);
                    tabButtons.get(i).setOpaque(false);
                    tabButtons.get(i).setContentAreaFilled(false);
                }
                tabButtons.get(i).setBorderPainted(false);
            }
            parent.setActiveTab(idx, cardNames); // Call AdminMain to switch form
        };

        // Add listeners to each button
        for (int i = 0; i < tabButtons.size(); i++) {
            final int idx = i;
            tabButtons.get(i).addActionListener(e -> setActiveTab.accept(idx));
        }

        // Set the first tab as active by default
        setActiveTab.accept(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        LeaveManagementButton = new SideTabButton("HR1");
        RosterAssignmentButton = new SideTabButton("HR2");
        TeamsAndMembersButton = new SideTabButton("HR7");
        StaffAttendanceButton = new SideTabButton("HR3");
        LogoutButton = new SideTabButton("HR6");
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(81, 81, 81));
        setPreferredSize(new java.awt.Dimension(180, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaveManagementButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaveManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        LeaveManagementButton.setText("Leave Management");
        LeaveManagementButton.setPreferredSize(new java.awt.Dimension(140, 40));
        add(LeaveManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, -1));

        RosterAssignmentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RosterAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        RosterAssignmentButton.setText("Roster Assignment");
        RosterAssignmentButton.setPreferredSize(new java.awt.Dimension(140, 40));
        add(RosterAssignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 180, -1));

        TeamsAndMembersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TeamsAndMembersButton.setForeground(new java.awt.Color(255, 255, 255));
        TeamsAndMembersButton.setText("Teams & Members");
        TeamsAndMembersButton.setPreferredSize(new java.awt.Dimension(140, 40));
        TeamsAndMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamsAndMembersButtonActionPerformed(evt);
            }
        });
        add(TeamsAndMembersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 180, -1));

        StaffAttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StaffAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        StaffAttendanceButton.setText("Staff Attendance");
        StaffAttendanceButton.setPreferredSize(new java.awt.Dimension(140, 40));
        add(StaffAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 297, 180, -1));

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teamleader");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
            parent.dispose();
            Login log = new Login();
            log.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void TeamsAndMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamsAndMembersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamsAndMembersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LeaveManagementButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton RosterAssignmentButton;
    private javax.swing.JButton StaffAttendanceButton;
    private javax.swing.JButton TeamsAndMembersButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
